language: java
jdk: oraclejdk8

install:
  - echo "Overriding default Travis install step to avoid useless Gradle invocations."

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    on:
      tags: true

notifications:
  email: false
